// apps/website2/src/components/layout/Navbar/Navbar.vue
<script setup lang="ts">
import { IconMenu2, IconMoon, IconSun } from "@tabler/icons-vue";
import { IconButton } from "$components/ui/icon-button";
import DesktopLinks from "./DesktopLinks.vue";
import { colorSchemeToggle } from "./Navbar.styles";
import { Box, Container, HStack, styled } from "$styled-system/jsx";

const colorMode = useColorMode();

const toggleColorScheme = () => {
	console.log(colorMode);
	if (colorMode.preference === "light") {
		colorMode.preference = "dark";
	} else {
		colorMode.preference = "light";
	}
};
</script>

<template>
	<styled.nav bg="bg.default" pos="sticky" top="0" zIndex="sticky">
		<Box borderBottomWidth="1px" pos="relative">
			<Container :py="{ base: 3, md: 4 }" maxW="7xl">
				<HStack gap="8" justify="space-between">
					<HStack gap="10">
						<DesktopLinks />
					</HStack>
					<HStack gap="1">
						<IconButton @click="toggleColorScheme()" variant="ghost">
							<IconSun :class="colorSchemeToggle({ variant: 'sun' })" />
							<IconMoon :class="colorSchemeToggle({ variant: 'moon' })" />
						</IconButton>
						<IconButton :display="{ base: 'flex', lg: 'none' }" variant="ghost">
							<IconMenu2 />
						</IconButton>
					</HStack>
				</HStack>
			</Container>
		</Box>
	</styled.nav>
</template>

// apps/website/src/components/layout/Navbar/Navbar.svelte
<script lang="ts">
	import { Menu2, Moon, Sun } from "tabler-icons-svelte";
	import DesktopLinks from "./DesktopLinks.svelte";
	import MobileDrawer from "./MobileDrawer.svelte";
	import { colorSchemeToggle } from "./Navbar.styles";
	import IconButton from "$components/ui/icon-button/IconButton.svelte";
	import { colorSchemeStore } from "$stores/color-scheme";
	import { css } from "$styled-system/css";
	import { container, hstack } from "$styled-system/patterns";

	function toggleColorScheme() {
		if ($colorSchemeStore === "light") {
			colorSchemeStore.set("dark");
		} else {
			colorSchemeStore.set("light");
		}
	}
</script>

<nav class={css({ pos: "sticky", top: 0, zIndex: "sticky", bg: "bg.default" })}>
	<div class={css({ pos: "relative", borderBottomWidth: "1px" })}>
		<div class={container({ py: { base: 3, md: 4 }, maxW: "7xl" })}>
			<section class={hstack({ justify: "space-between", gap: 8 })}>
				<div class={hstack({ gap: 10 })}>
					<DesktopLinks />
				</div>
				<section class={hstack({ gap: 1 })}>
					<IconButton variant="tertiary" on:click={toggleColorScheme}>
						<Sun class={colorSchemeToggle({ variant: "sun" })} />
						<Moon class={colorSchemeToggle({ variant: "moon" })} />
					</IconButton>
					<MobileDrawer>
						<IconButton
							css={{
								display: {
									base: "flex",
									lg: "none",
								},
							}}
							variant="tertiary"
						>
							<Menu2 />
						</IconButton>
					</MobileDrawer>
				</section>
			</section>
		</div>
	</div>
</nav>
